[project]
name = "qa-devops"
version = "0.1.0"
description = "Simple Web App for Completing the Software Engineering and DevOps Assignment with QA"
requires-python = ">=3.9"
dependencies = [
    "bcrypt",
    "flask",
    "flask-limiter",
    "flask-login",
    "flask-wtf",
    "gunicorn",
    "psycopg2-binary",
    "python-dotenv",
    "retrying"
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tst"]
